# Site
name: "HEALWON"
title: "healwon's blog"
description: "healwon's blog"
baseurl: ""
url: "https://healwon.github.io"
logo: 'assets/images/logo.png'
disqus: "healwon's blog"
email: woni9911@gmail.com
locale: ko-KR

# Authors
authors:
  healwon:
    name: healwon
    display_name: healwon
    email: woni9911@gmail.com
    github: healwon
    web: https://healwon.github.io/about
    description: "Undergraduate in Korea. E-mail:woni9911@gmail.com"

# Outputting
permalink: /:categories/:title/
paginate: 9
paginate_path: /page:num/
timezone: Asia/Seoul
title_seperator: "-"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# defaults
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true 

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

include: ["_pages"]

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
